name: Build all Hatch images

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the frontend UI Docker image
      run: docker build ./frontend --file frontend/delivery/Dockerfile --tag hatch-ui:latest

    - name: Build the backend API Server Docker image
      run: docker build ./backend --file backend/delivery/api-server/Dockerfile --tag hatch-api-server:latest
